os: Visual Studio 2017

environment:
    BOOST_ROOT: C:\Libraries\boost_1_67_0
    BOOST_LIBRARYDIR: C:\Libraries\boost_1_67_0\lib64-msvc-14

build_script:
    - md build
    - cd build
    - cmake -G "Visual Studio 15 2017 Win64" ..
    - MSBuild lithe.sln /p:Configuration=Release /m
   
after_build: 
  - if not defined APPVEYOR_BUILD_NUMBER (set APPVEYOR_BUILD_NUMBER=%APPVEYOR_BUILD_ID%)
  - cd src\Release
  - mkdir lithe-%APPVEYOR_BUILD_NUMBER%
  - copy *.exe lithe-%APPVEYOR_BUILD_NUMBER%
  - copy ..\..\..\LICENSE lithe-%APPVEYOR_BUILD_NUMBER%
  - 7z a lithe-%APPVEYOR_BUILD_NUMBER%-windows.zip lithe-%APPVEYOR_BUILD_NUMBER%
  - copy lithe-%APPVEYOR_BUILD_NUMBER%-windows.zip ..\..\..\
  
artifacts:
  - path: lithe-$(APPVEYOR_BUILD_NUMBER)-windows.zip
    name: Lithe-Release

on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:DISCORD_WEBHOOK

on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:DISCORD_WEBHOOK